import 'package:flutter/material.dart';
import 'package:sunbird/globals/globals_export.dart';
import 'package:sunbird/views/tutorial/tutorial_text.dart';
import 'package:sunbird/views/tutorial/widgets/body_text_widget.dart';
import 'package:sunbird/views/tutorial/widgets/sub_title_text.dart';
import 'package:sunbird/views/tutorial/widgets/text_body_divider.dart';

class TutorialBarcodesView extends StatefulWidget {
  const TutorialBarcodesView({Key? key}) : super(key: key);

  @override
  State<TutorialBarcodesView> createState() => _TutorialBarcodesViewState();
}

class _TutorialBarcodesViewState extends State<TutorialBarcodesView> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: _appBar(),
      body: _body(),
    );
  }

  AppBar _appBar() {
    return AppBar(
      title: Text(
        'Barcode Tutorial',
        style: Theme.of(context).textTheme.titleMedium,
      ),
      centerTitle: true,
    );
  }

  Widget _body() {
    return SingleChildScrollView(
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // ExpansionTile(
            //   title: SubTitleText(
            //     subTitle: '1. Barcode Generator',
            //   ),
            //   children: [
            //     BodyText(
            //       text:
            //           'Barcodes can be generated by the built in Barcode Generator.',
            //     ),
            //   ],
            // ),

            // TextBodyDivider(),

            // ///2. Barcode Sizing.
            // SubTitleText(
            //   subTitle: '2. Barcode Sizing',
            // ),
            // BodyText(
            //   text:
            //       'Depending on your aplication the barcode size is important.',
            // ),

            // TextBodyDivider(),

            // ///3. Barcode Placement.
            // SubTitleText(
            //   subTitle: '3. Barcode Placement',
            // ),
            // BodyText(
            //   text:
            //       'Depending on your aplication the barcode size is important.',
            // ),
          ],
        ),
      ),
    );
  }
}
