import 'package:isar/isar.dart';
part 'barcode_batch.g.dart';

///This stores details about barcodes generated by the user.
/// - Time of creation.
/// - Size of the barcodes.
/// - The number of the first barcode.
/// - The number of the last barcode.
/// - Imported ?
@Collection()
@Name("BarcodeBatch")
class BarcodeBatch {
  Id id = Isar.autoIncrement;

  //Generation Time.
  @Name("timestamp")
  late int timestamp;

  ///Side length (mm)
  @Name("width")
  late double width;

  ///Side length (mm)
  @Name("height")
  late double height;

  ///Barcode range start.
  @Name("rangeStart")
  late int rangeStart;

  ///Barcode range end.
  @Name("rangeEnd")
  late int rangeEnd;

  ///Barcode Size.
  @Name("imported")
  late bool imported;

  @override
  String toString() {
    return '\ntimestamp: $timestamp, h: $height, w: $width';
  }

  @ignore
  DateTime get creationDateTime {
    return DateTime.fromMillisecondsSinceEpoch(timestamp);
  }
}
