import 'package:isar/isar.dart';
part 'barcode_batch.g.dart';

///This stores details about barcodes generated by the user.
/// - Time of creation.
/// - Size of the barcodes.
/// - The number of the first barcode.
/// - The number of the last barcode.
/// - Imported ?
@Collection()
@Name("BarcodeBatch")
class BarcodeBatch {
  Id id = Isar.autoIncrement;

  late String uuid;
  late int amount;

  // Time of creation.
  late int? timestamp;

  /// The width/height of the barcode batch.
  /// If this is null then the barcodes in this batch does not have the same sizes.
  late double? width; // (mm)
  late double? height; // (mm)
  late bool imported;

  @override
  String toString() {
    return '\ntimestamp: $timestamp, h: $height, w: $width';
  }

  @ignore
  DateTime? get creationDateTime {
    if (timestamp == null) return null;
    return DateTime.fromMillisecondsSinceEpoch(timestamp!);
  }

  @ignore
  bool get canPrint => width != null && height != null;
}
